import { useMemo, useState } from "react";
import { ArrowRight, Award, BookOpen, CheckCircle2, Menu, Phone, ShieldCheck, Sparkles, Star, Target, Users, X, Zap } from "lucide-react";

type Q = [string, string, string[], number];
type Course = { title: string; price: string; text: string };

const subjects = ["Українська мова", "Математика", "Історія України", "Англійська мова", "Біологія", "Географія", "Фізика", "Хімія"];
const nav = [["Головна", "home"], ["Предмети", "subjects"], ["Тест", "tests"], ["Ціни", "prices"], ["Відгуки", "reviews"], ["Заявка", "contact"]];
const courses: Course[] = [
  { title: "Група", price: "300 грн", text: "Заняття в невеликій групі. Багато практики й розбір помилок." },
  { title: "Індивідуально", price: "600 грн", text: "Особистий темп, слабкі теми й план під конкретний бал." },
  { title: "Абонемент 5 занять", price: "4000 грн", text: "Пакет для швидкого старту або точкового ривка перед НМТ." },
  { title: "Група 10 занять", price: "2500 грн", text: "Регулярна підготовка в групі за вигідною ціною." },
];
const reviews = [
  ["Математика", "Марія, 11 клас", "Раніше пробники були біля 150. Після занять стала спокійніше розв’язувати задачі. Останній результат — 180."],
  ["Українська мова", "Артем, випускник", "Нарешті розклав наголоси й пунктуацію. Без води: правило, приклад, практика."],
  ["Історія України", "Софія, 11 клас", "Дати перестали бути кашею. План повторення реально допоміг зв’язати події між собою."],
  ["Підготовка", "Данило, 10 клас", "Пройшов тест, побачив результат і залишив заявку. Все просто, без зайвих кроків."],
];
const quiz: Record<string, Q[]> = {
  "Українська мова": [["2023", "Правильний наголос", ["вИпадок", "випАдок", "катАлог", "дОнька"], 1], ["2024", "Правильне написання", ["будь який", "пів-Європи", "хтозна що", "пів яблука"], 1], ["2025", "Речення без помилки", ["Дякую вас", "Навчаюся української", "Згідно наказу", "Вибачив мене"], 1], ["2026", "Де потрібен апостроф?", ["бур'ян", "свято", "цвях", "морквяний"], 0], ["2023", "Синоніми", ["сміливий, хоробрий", "високий, низький", "швидкий, тихий", "добрий, злий"], 0], ["2024", "Складне речення", ["Сонце зайшло, і місто стихло.", "Учні слухали.", "Книги лежали.", "Ми прийшли."], 0], ["2025", "Правильний прийменник", ["по причині", "через хворобу", "по закінченню", "згідно розкладу"], 1], ["2026", "«Тримати язик за зубами»", ["мовчати", "лінуватися", "обманювати", "запам'ятати"], 0], ["2023", "Префікс пре-", ["премудрий", "приїхати", "пришити", "присісти"], 0], ["2024", "Кома", ["Коли зійшло сонце ми рушили.", "Коли зійшло сонце, ми рушили.", "Коли, зійшло сонце ми рушили.", "Коли зійшло, сонце ми рушили."], 1]],
  "Математика": [["2023", "15% від 200", ["15", "20", "30", "45"], 2], ["2024", "3x - 6 = 12", ["2", "4", "6", "8"], 2], ["2025", "Площа 6×8", ["14", "28", "48", "64"], 2], ["2026", "x² = 49", ["5", "6", "7", "8"], 2], ["2023", "2³ + 4²", ["12", "20", "24", "32"], 1], ["2024", "Середнє 4,8,12", ["6", "8", "10", "12"], 1], ["2025", "2a+3, a=5", ["10", "11", "13", "15"], 2], ["2026", "Прямий кут", ["45°", "60°", "90°", "120°"], 2], ["2023", "4x+3x", ["7x", "12x", "x", "7x²"], 0], ["2024", "Периметр квадрата 9", ["18", "27", "36", "81"], 2]],
  "Історія України": [["2023", "Незалежність України", ["1989", "1990", "1991", "1996"], 2], ["2024", "Конституція Орлика", ["Хмельницький", "Пилип Орлик", "Мазепа", "Грушевський"], 1], ["2025", "Конституція України", ["1991", "1994", "1996", "2004"], 2], ["2026", "Перший президент", ["Кравчук", "Кучма", "Ющенко", "Грушевський"], 0], ["2023", "Галицько-Волинська держава", ["Львів", "Галич", "Київ", "Чернігів"], 1], ["2024", "Центральна Рада", ["Петлюра", "Грушевський", "Скоропадський", "Коновалець"], 1], ["2025", "Берестейська унія", ["1569", "1596", "1648", "1709"], 1], ["2026", "Війна Хмельницького", ["1596", "1648", "1654", "1709"], 1], ["2023", "Акт Злуки", ["22.01.1919", "24.08.1991", "28.06.1996", "01.12.1991"], 0], ["2024", "Референдум", ["24.08.1991", "01.12.1991", "28.06.1996", "16.07.1990"], 1]],
  "Англійська мова": [["2023", "She ___ to school.", ["go", "goes", "going", "gone"], 1], ["2024", "Synonym of quick", ["slow", "fast", "late", "weak"], 1], ["2025", "I have lived here ___ 2020", ["for", "since", "during", "by"], 1], ["2026", "___ you like coffee?", ["Do", "Does", "Are", "Have"], 0], ["2023", "Opposite of expensive", ["cheap", "rich", "large", "modern"], 0], ["2024", "We ___ watching", ["is", "are", "am", "be"], 1], ["2025", "He ___ homework yesterday", ["do", "does", "did", "done"], 2], ["2026", "Choose a noun", ["beautiful", "quickly", "teacher", "run"], 2], ["2023", "There ___ students", ["is", "are", "am", "was"], 1], ["2024", "___ apple", ["A", "An", "The", "-"], 1]],
  "Біологія": [["2023", "Фотосинтез", ["Мітохондрія", "Рибосома", "Хлоропласт", "Ядро"], 2], ["2024", "Спадкова інформація", ["ДНК", "АТФ", "Глюкоза", "Вода"], 0], ["2025", "Клітина крові", ["Еритроцит", "Нейрон", "Остеоцит", "Хлоропласт"], 0], ["2026", "Статеві клітини", ["Мітоз", "Мейоз", "Фотосинтез", "Дихання"], 1], ["2023", "Транспорт речовин", ["Кровоносна", "Нервова", "Опорна", "Покривна"], 0], ["2024", "Одиниця будови", ["Орган", "Тканина", "Клітина", "Молекула"], 2], ["2025", "Продуценти", ["Рослини", "Гриби", "Хижаки", "Бактерії"], 0], ["2026", "Гормон глюкози", ["Адреналін", "Інсулін", "Тироксин", "Тестостерон"], 1], ["2023", "Дихання клітини", ["Мітохондрії", "Хлоропласти", "Вакуолі", "Рибосоми"], 0], ["2024", "Хромосоми", ["спадковість", "травлення", "дихання", "рух"], 0]],
  "Географія": [["2023", "Найбільший океан", ["Атлантичний", "Індійський", "Тихий", "Північний"], 2], ["2024", "Столиця Канади", ["Торонто", "Оттава", "Монреаль", "Ванкувер"], 1], ["2025", "Найвища гора", ["Кіліманджаро", "Еверест", "Монблан", "Говерла"], 1], ["2026", "Найдовша річка України", ["Дністер", "Південний Буг", "Дніпро", "Сіверський Донець"], 2], ["2023", "Екватор", ["Схід/Захід", "Північ/Південь", "Материки", "Пояси"], 1], ["2024", "Говерла", ["Карпати", "Крим", "Альпи", "Кавказ"], 0], ["2025", "Найбільша пустеля", ["Сахара", "Антарктична", "Гобі", "Калахарі"], 1], ["2026", "Південна півкуля", ["Євразія", "Африка", "Австралія", "Північна Америка"], 2], ["2023", "Масштаб показує", ["висоту", "відстані", "клімат", "населення"], 1], ["2024", "Клімат України", ["арктичний", "помірний", "тропічний", "екваторіальний"], 1]],
  "Фізика": [["2023", "Одиниця сили", ["Джоуль", "Ньютон", "Ват", "Паскаль"], 1], ["2024", "Швидкість", ["шлях/час", "час/шлях", "маса/об'єм", "сила/площа"], 0], ["2025", "Потужність", ["Ват", "Ньютон", "Джоуль", "Кулон"], 0], ["2026", "Рідина в газ", ["Плавлення", "Кристалізація", "Випаровування", "Конденсація"], 2], ["2023", "Тяжіння", ["на метали", "на тіла з масою", "на рідини", "лише в космосі"], 1], ["2024", "Струм", ["хаос молекул", "рух зарядів", "температура", "світло"], 1], ["2025", "Напруга", ["Ампер", "Вольт", "Ом", "Ват"], 1], ["2026", "Тиск", ["сила/площа", "маса/об'єм", "шлях/час", "робота/час"], 0], ["2023", "Світло", ["300 км/с", "300 000 км/с", "30 000 км/с", "3 000 км/с"], 1], ["2024", "Вимір сили", ["термометр", "динамометр", "барометр", "амперметр"], 1]],
  "Хімія": [["2023", "Формула води", ["CO₂", "O₂", "H₂O", "NaCl"], 2], ["2024", "Порядковий номер", ["нейтрони", "протони", "молекули", "ізотопи"], 1], ["2025", "NaCl", ["вода", "сіль", "CO₂", "кисень"], 1], ["2026", "Символ кисню", ["O", "K", "C", "N"], 0], ["2023", "Прискорюють реакції", ["каталізатори", "індикатори", "розчинники", "окисники"], 0], ["2024", "pH < 7", ["кисле", "лужне", "нейтральне", "газове"], 0], ["2025", "CO₂", ["чадний газ", "вуглекислий газ", "кисень", "водень"], 1], ["2026", "Метали", ["електропровідність", "газ", "скло", "не проводять тепло"], 0], ["2023", "Атом", ["ядро й електрони", "молекули", "кристали", "солі"], 0], ["2024", "Горіння", ["кисень", "азот", "гелій", "аргон"], 0]],
};

function scrollTo(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }

export default function CleanLanding() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [subject, setSubject] = useState(subjects[0]);
  const [index, setIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<string, number>>({});
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [sent, setSent] = useState(false);
  const [sending, setSending] = useState(false);
  const questions = quiz[subject];
  const question = questions[index];
  const key = `${subject}-${index}`;
  const picked = answers[key];
  const score = useMemo(() => questions.reduce((sum, item, itemIndex) => sum + (answers[`${subject}-${itemIndex}`] === item[3] ? 1 : 0), 0), [answers, questions, subject]);
  const answered = questions.filter((_, itemIndex) => answers[`${subject}-${itemIndex}`] !== undefined).length;

  function choose(optionIndex: number) {
    setAnswers((current) => ({ ...current, [key]: optionIndex }));
    if (index < 9) window.setTimeout(() => setIndex((value) => Math.min(9, value + 1)), 520);
  }

  function openSubject(next: string) {
    setSubject(next);
    setIndex(0);
    scrollTo("tests");
  }

  async function courseClick(course: Course) {
    fetch("/api/lead", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "Оплата курсу", name: "Клік по оплаті", phone: "", subject: course.title, score: course.price }) }).catch(() => undefined);
    scrollTo("contact");
  }

  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSending(true);
    const payload = { type: "Заявка", name, phone, subject, score: `${score}/10` };
    localStorage.setItem("nmthub-lead", JSON.stringify({ ...payload, createdAt: new Date().toISOString() }));
    try { await fetch("/api/lead", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); } catch { /* silent */ }
    setSending(false);
    setSent(true);
  }

  return <main className="site" id="home"><div className="orb orb-a" /><div className="orb orb-b" />
    <header className="header float-in"><button className="logo" onClick={() => scrollTo("home")}><span>NH</span><strong>NMT<span>Hub</span></strong></button><nav className="nav">{nav.map(([label, id]) => <button key={id} onClick={() => scrollTo(id)}>{label}</button>)}</nav><button className="header-cta" onClick={() => scrollTo("contact")}>Записатися</button><button className="menu-button" onClick={() => setMenuOpen(true)} aria-label="Відкрити меню"><Menu size={22} /></button></header>
    {menuOpen && <div className="mobile-panel"><button className="close-button" onClick={() => setMenuOpen(false)} aria-label="Закрити меню"><X size={22} /></button>{nav.map(([label, id]) => <button key={id} onClick={() => { setMenuOpen(false); scrollTo(id); }}>{label}</button>)}</div>}
    <section className="hero section"><div className="hero-text reveal-up"><div className="label"><Sparkles size={16} /> Підготовка до НМТ 2027</div><h1>Здай НМТ на максимум</h1><p>Короткий тест покаже стартовий рівень. Після заявки ми підберемо формат підготовки й пояснимо, з чого почати.</p><div className="hero-actions"><button className="primary" onClick={() => scrollTo("tests")}>Пройти тест <ArrowRight size={18} /></button><button className="secondary" onClick={() => scrollTo("prices")}>Дивитися ціни</button></div></div><div className="hero-card reveal-up delay-1"><div className="score pulse-score">200</div><h2>200 — реальна ціль</h2><p>Здати НМТ на 200 з NMTHub — це можливо. Залиште заявку, і ми з вами зв’яжемося.</p><div className="card-list"><span><CheckCircle2 size={17} /> Тест в одному вікні</span><span><CheckCircle2 size={17} /> Питання змінюються після відповіді</span><span><CheckCircle2 size={17} /> Менеджер зв’яжеться після заявки</span></div></div></section>
    <section className="stats reveal-up"><article><strong>8</strong><span>предметів</span></article><article><strong>80</strong><span>питань</span></article><article><strong>{score}/10</strong><span>твій тест-бал</span></article><article><strong>{answered}/10</strong><span>відповідей</span></article></section>
    <section className="section" id="subjects"><div className="section-head"><div className="label"><BookOpen size={16} /> Предмети</div><h2>Обери предмет</h2><p>Почни з короткого тесту. Він покаже, з яких тем краще стартувати.</p></div><div className="subject-grid">{subjects.map((item, itemIndex) => <article className={item === subject ? "subject interactive-card active-subject" : "subject interactive-card"} key={item}><span>{String(itemIndex + 1).padStart(2, "0")}</span><h3>{item}</h3><p>10 питань у форматі підготовки до НМТ.</p><button onClick={() => openSubject(item)}>Відкрити тест</button></article>)}</div></section>
    <section className="section tests-section" id="tests"><div className="section-head"><div className="label"><Zap size={16} /> Тест</div><h2>{subject}</h2><p>Один екран. Одна відповідь. Далі одразу наступне питання.</p></div><div className="single-quiz"><div className="quiz-progress"><span>Питання {index + 1} / 10</span><b>{score}/10</b></div><div className="quiz-bar"><i style={{ width: `${Math.max(((answered || index + 1) / 10) * 100, 10)}%` }} /></div><article key={key} className={picked !== undefined ? (picked === question[3] ? "quiz-card single correct" : "quiz-card single wrong") : "quiz-card single"}><div className="quiz-top"><span>{question[0]}</span>{picked !== undefined && <b>{picked === question[3] ? "+1" : "0"}</b>}</div><h3>{index + 1}. {question[1]}</h3><div className="quiz-options">{question[2].map((option, optionIndex) => <button key={option} className={picked === optionIndex ? "picked" : ""} onClick={() => choose(optionIndex)}>{option}</button>)}</div></article><div className="quiz-actions"><button className="secondary" onClick={() => setIndex((value) => Math.max(0, value - 1))}>Назад</button><button className="primary" onClick={() => setIndex((value) => Math.min(9, value + 1))}>Далі</button></div>{answered === 10 && <div className="quiz-result"><CheckCircle2 size={28} /><strong>Результат: {score}/10</strong><p>Залиш заявку, і ми підберемо формат підготовки під твій рівень.</p><button className="primary" onClick={() => scrollTo("contact")}>Записатися</button></div>}</div></section>
    <section className="section process"><div className="section-head left"><div className="label"><Target size={16} /> План</div><h2>Без хаосу в підготовці</h2><p>Спочатку бачимо рівень. Потім збираємо план: теми, практика, повторення і контроль прогресу.</p></div><div className="process-grid"><article className="process-card interactive-card"><span>1</span><h3>Тест</h3><p>Учень проходить 10 питань і бачить стартовий результат.</p></article><article className="process-card interactive-card"><span>2</span><h3>Розбір</h3><p>Фіксуємо слабкі теми й не витрачаємо час на те, що вже виходить.</p></article><article className="process-card interactive-card"><span>3</span><h3>Заняття</h3><p>Працюємо в групі або індивідуально — залежно від цілі та темпу.</p></article></div></section>
    <section className="section benefits"><div className="benefit-card interactive-card"><Award /><strong>Фокус на балах</strong><p>Готуємо не “для галочки”, а під конкретний результат на НМТ.</p></div><div className="benefit-card interactive-card"><Users /><strong>Людський темп</strong><p>Пояснюємо спокійно. Без тиску, але з дисципліною.</p></div><div className="benefit-card interactive-card"><ShieldCheck /><strong>Контроль прогресу</strong><p>Після тестів видно, де вже краще, а де ще треба повторити.</p></div><div className="benefit-card interactive-card"><Star /><strong>Практика</strong><p>Менше теорії заради теорії. Більше завдань і розбору помилок.</p></div></section>
    <section className="section" id="prices"><div className="section-head"><div className="label"><Star size={16} /> Ціни</div><h2>Формат під твою ціль</h2><p>Можна почати з групи, взяти індивідуальне заняття або одразу забронювати пакет.</p></div><div className="price-grid rich-prices">{courses.map((course, itemIndex) => <article className={itemIndex === 1 ? "price featured" : "price"} key={course.title}>{itemIndex === 1 && <span className="popular">Популярний</span>}<h3>{course.title}</h3><strong>{course.price}</strong><p>{course.text}</p><ul><li><CheckCircle2 size={16} /> План підготовки</li><li><CheckCircle2 size={16} /> Практика</li><li><CheckCircle2 size={16} /> Контроль прогресу</li></ul><button onClick={() => courseClick(course)}>Оплатити курс</button></article>)}</div></section>
    <section className="section" id="reviews"><div className="section-head"><div className="label"><Award size={16} /> Відгуки</div><h2>Що кажуть учні</h2><p>Коротко і по суті: що змінилось після підготовки.</p></div><div className="reviews">{reviews.map(([subjectName, author, text]) => <article key={`${subjectName}-${author}`} className="interactive-card"><div>★★★★★</div><h3>{subjectName}</h3><p>{text}</p><span className="review-author">{author}</span></article>)}</div></section>
    <section className="section contact" id="contact"><div><div className="label"><Phone size={16} /> Заявка</div><h2>Залиш заявку</h2><p>Напиши ім’я та телефон. Менеджер зв’яжеться з тобою і допоможе вибрати формат занять.</p></div><form className="form" onSubmit={submit}>{sent ? <div className="success"><CheckCircle2 size={42} /><h3>Заявку прийнято</h3><p>Менеджер скоро зв'яжеться з вами.</p><button type="button" onClick={() => setSent(false)}>Ще раз</button></div> : <><label>Ім'я<input aria-label="Ім'я" value={name} onChange={(event) => setName(event.target.value)} placeholder="Ваше ім'я" required /></label><label>Телефон<input aria-label="Телефон" value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="+380..." required /></label><label>Предмет<select aria-label="Предмет" value={subject} onChange={(event) => setSubject(event.target.value)}>{subjects.map((item) => <option key={item}>{item}</option>)}</select></label><div className="result-pill">Результат тесту: <b>{score}/10</b></div><button className="primary" type="submit" disabled={sending}>{sending ? "Надсилаємо..." : "Надіслати заявку"} <ArrowRight size={18} /></button></>}</form></section>
    <footer className="footer"><div className="logo"><span>NH</span><strong>NMT<span>Hub</span></strong></div><p>© 2026 NMTHub. Підготовка до НМТ.</p></footer>
  </main>;
}
