import { useMemo, useState } from "react";
import { ArrowRight, Award, BookOpen, CheckCircle2, Menu, Phone, ShieldCheck, Sparkles, Star, Target, Users, X, Zap } from "lucide-react";

type Question = [string, string[], number];
type Course = { title: string; price: string; text: string };

const subjects = ["Українська мова", "Математика", "Історія України", "Англійська мова", "Біологія", "Географія", "Фізика", "Хімія"];
const nav = [["Головна", "home"], ["Предмети", "subjects"], ["Тест", "tests"], ["Ціни", "prices"], ["Відгуки", "reviews"], ["Заявка", "contact"]];
const courses: Course[] = [
  { title: "Група", price: "300 грн", text: "Заняття в невеликій групі. Багато практики й розбір помилок." },
  { title: "Індивідуально", price: "600 грн", text: "Особистий темп, слабкі теми й план під конкретний бал." },
  { title: "Абонемент 5 занять", price: "4000 грн", text: "Пакет для старту або швидкого повторення перед тестом." },
  { title: "Група 10 занять", price: "2500 грн", text: "Регулярна підготовка в групі за вигіднішою ціною." },
];
const reviews = [
  ["Математика", "Марія, 11 клас", "На пробниках довго стояла біля 150. Після занять стала розуміти, де саме помиляюсь. Останній результат — 180."],
  ["Українська мова", "Артем, випускник", "Сподобалось, що не було довгих лекцій. Правило, приклад, завдання — і відразу видно, що запам’ятав."],
  ["Історія України", "Софія, 11 клас", "Раніше дати просто плутались. Коли дали нормальний план повторення, події почали складатися в логіку."],
  ["Підготовка", "Ілля, 11 клас", "Пройшов тест, побачив результат і залишив заявку. Далі мені пояснили, який формат краще взяти."],
];
const quiz: Record<string, Question[]> = {
  "Українська мова": [["Оберіть слово з правильним наголосом", ["вИпадок", "випАдок", "катАлог", "дОнька"], 1], ["Оберіть правильне написання", ["будь який", "пів-Європи", "хтозна що", "пів яблука"], 1], ["Оберіть речення без граматичної помилки", ["Дякую вас", "Навчаюся української", "Згідно наказу", "Вибачив мене"], 1], ["У якому слові потрібен апостроф?", ["бур'ян", "свято", "цвях", "морквяний"], 0], ["Оберіть синоніми", ["сміливий, хоробрий", "високий, низький", "швидкий, тихий", "добрий, злий"], 0], ["Оберіть складне речення", ["Сонце зайшло, і місто стихло.", "Учні слухали.", "Книги лежали.", "Ми прийшли."], 0], ["Оберіть правильний прийменник", ["по причині", "через хворобу", "по закінченню", "згідно розкладу"], 1], ["Що означає фразеологізм «тримати язик за зубами»?", ["мовчати", "лінуватися", "обманювати", "запам'ятати"], 0], ["У якому слові пишемо префікс пре-?", ["премудрий", "приїхати", "пришити", "присісти"], 0], ["Оберіть речення з правильною комою", ["Коли зійшло сонце ми рушили.", "Коли зійшло сонце, ми рушили.", "Коли, зійшло сонце ми рушили.", "Коли зійшло, сонце ми рушили."], 1]],
  "Математика": [["15% від 200 дорівнює", ["15", "20", "30", "45"], 2], ["Розв’яжіть рівняння: 3x - 6 = 12", ["2", "4", "6", "8"], 2], ["Площа прямокутника 6×8", ["14", "28", "48", "64"], 2], ["x² = 49. Додатний корінь", ["5", "6", "7", "8"], 2], ["2³ + 4² =", ["12", "20", "24", "32"], 1], ["Середнє чисел 4, 8, 12", ["6", "8", "10", "12"], 1], ["2a + 3, якщо a = 5", ["10", "11", "13", "15"], 2], ["Прямий кут дорівнює", ["45°", "60°", "90°", "120°"], 2], ["Спростіть: 4x + 3x", ["7x", "12x", "x", "7x²"], 0], ["Периметр квадрата зі стороною 9", ["18", "27", "36", "81"], 2]],
  "Історія України": [["Україна проголосила незалежність у", ["1989", "1990", "1991", "1996"], 2], ["Автор Конституції 1710 року", ["Хмельницький", "Пилип Орлик", "Мазепа", "Грушевський"], 1], ["Конституцію України ухвалено у", ["1991", "1994", "1996", "2004"], 2], ["Перший президент незалежної України", ["Кравчук", "Кучма", "Ющенко", "Грушевський"], 0], ["Один із центрів Галицько-Волинської держави", ["Львів", "Галич", "Київ", "Чернігів"], 1], ["Голова Центральної Ради", ["Петлюра", "Грушевський", "Скоропадський", "Коновалець"], 1], ["Берестейська унія", ["1569", "1596", "1648", "1709"], 1], ["Початок повстання Хмельницького", ["1596", "1648", "1654", "1709"], 1], ["Акт Злуки УНР і ЗУНР", ["22.01.1919", "24.08.1991", "28.06.1996", "01.12.1991"], 0], ["Всеукраїнський референдум про незалежність", ["24.08.1991", "01.12.1991", "28.06.1996", "16.07.1990"], 1]],
  "Англійська мова": [["She ___ to school every day.", ["go", "goes", "going", "gone"], 1], ["Synonym of quick", ["slow", "fast", "late", "weak"], 1], ["I have lived here ___ 2020", ["for", "since", "during", "by"], 1], ["___ you like coffee?", ["Do", "Does", "Are", "Have"], 0], ["Opposite of expensive", ["cheap", "rich", "large", "modern"], 0], ["We ___ watching a film now.", ["is", "are", "am", "be"], 1], ["He ___ homework yesterday.", ["do", "does", "did", "done"], 2], ["Choose a noun", ["beautiful", "quickly", "teacher", "run"], 2], ["There ___ many students here.", ["is", "are", "am", "was"], 1], ["___ apple a day keeps the doctor away.", ["A", "An", "The", "-"], 1]],
  "Біологія": [["Де відбувається фотосинтез?", ["Мітохондрія", "Рибосома", "Хлоропласт", "Ядро"], 2], ["Носій спадкової інформації", ["ДНК", "АТФ", "Глюкоза", "Вода"], 0], ["Клітина крові", ["Еритроцит", "Нейрон", "Остеоцит", "Хлоропласт"], 0], ["Утворення статевих клітин", ["Мітоз", "Мейоз", "Фотосинтез", "Дихання"], 1], ["Система транспорту речовин", ["Кровоносна", "Нервова", "Опорна", "Покривна"], 0], ["Основна одиниця будови організму", ["Орган", "Тканина", "Клітина", "Молекула"], 2], ["Продуценти в екосистемі", ["Рослини", "Гриби", "Хижаки", "Бактерії"], 0], ["Гормон, що регулює глюкозу", ["Адреналін", "Інсулін", "Тироксин", "Тестостерон"], 1], ["Клітинне дихання пов’язане з", ["Мітохондріями", "Хлоропластами", "Вакуолями", "Рибосомами"], 0], ["Хромосоми відповідають за", ["спадковість", "травлення", "дихання", "рух"], 0]],
  "Географія": [["Найбільший океан", ["Атлантичний", "Індійський", "Тихий", "Північний"], 2], ["Столиця Канади", ["Торонто", "Оттава", "Монреаль", "Ванкувер"], 1], ["Найвища гора світу", ["Кіліманджаро", "Еверест", "Монблан", "Говерла"], 1], ["Найдовша річка України", ["Дністер", "Південний Буг", "Дніпро", "Сіверський Донець"], 2], ["Екватор ділить Землю на", ["Схід/Захід", "Північ/Південь", "Материки", "Пояси"], 1], ["Говерла розташована в", ["Карпатах", "Криму", "Альпах", "Кавказі"], 0], ["Найбільша пустеля світу", ["Сахара", "Антарктична", "Гобі", "Калахарі"], 1], ["Материк у Південній півкулі", ["Євразія", "Африка", "Австралія", "Північна Америка"], 2], ["Масштаб показує", ["висоту", "відстані", "клімат", "населення"], 1], ["Клімат України переважно", ["арктичний", "помірний", "тропічний", "екваторіальний"], 1]],
  "Фізика": [["Одиниця сили", ["Джоуль", "Ньютон", "Ват", "Паскаль"], 1], ["Швидкість — це", ["шлях/час", "час/шлях", "маса/об'єм", "сила/площа"], 0], ["Одиниця потужності", ["Ват", "Ньютон", "Джоуль", "Кулон"], 0], ["Перехід рідини в газ", ["Плавлення", "Кристалізація", "Випаровування", "Конденсація"], 2], ["Сила тяжіння діє", ["на метали", "на тіла з масою", "на рідини", "лише в космосі"], 1], ["Електричний струм — це", ["хаос молекул", "рух зарядів", "температура", "світло"], 1], ["Одиниця напруги", ["Ампер", "Вольт", "Ом", "Ват"], 1], ["Тиск — це", ["сила/площа", "маса/об'єм", "шлях/час", "робота/час"], 0], ["Швидкість світла приблизно", ["300 км/с", "300 000 км/с", "30 000 км/с", "3 000 км/с"], 1], ["Силу вимірюють", ["термометром", "динамометром", "барометром", "амперметром"], 1]],
  "Хімія": [["Формула води", ["CO₂", "O₂", "H₂O", "NaCl"], 2], ["Порядковий номер показує кількість", ["нейтронів", "протонів", "молекул", "ізотопів"], 1], ["NaCl — це", ["вода", "сіль", "CO₂", "кисень"], 1], ["Символ кисню", ["O", "K", "C", "N"], 0], ["Речовини, що прискорюють реакції", ["каталізатори", "індикатори", "розчинники", "окисники"], 0], ["pH < 7 означає середовище", ["кисле", "лужне", "нейтральне", "газове"], 0], ["CO₂ — це", ["чадний газ", "вуглекислий газ", "кисень", "водень"], 1], ["Типова властивість металів", ["електропровідність", "газуватість", "прозорість", "крихкість"], 0], ["Атом має", ["ядро й електрони", "лише молекули", "лише кристали", "лише солі"], 0], ["Для горіння потрібен", ["кисень", "азот", "гелій", "аргон"], 0]],
};

function scrollTo(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }

export default function HumanLanding() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [subject, setSubject] = useState(subjects[0]);
  const [index, setIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<string, number>>({});
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [sent, setSent] = useState(false);
  const [sending, setSending] = useState(false);
  const questions = quiz[subject];
  const question = questions[index];
  const key = `${subject}-${index}`;
  const picked = answers[key];
  const score = useMemo(() => questions.reduce((sum, item, itemIndex) => sum + (answers[`${subject}-${itemIndex}`] === item[2] ? 1 : 0), 0), [answers, questions, subject]);
  const answered = questions.filter((_, itemIndex) => answers[`${subject}-${itemIndex}`] !== undefined).length;
  const wrong = Math.max(0, answered - score);
  const percent = Math.round((score / questions.length) * 100);
  const recommendation = score >= 8 ? "База вже сильна. Далі варто добити складні теми й тренувати швидкість." : score >= 5 ? "Є нормальний старт. Потрібно підтягнути слабкі теми й більше практикувати типові завдання." : "Починати краще з основ. Так буде спокійніше й без хаосу перед НМТ.";

  function choose(optionIndex: number) {
    setAnswers((current) => ({ ...current, [key]: optionIndex }));
    if (index < questions.length - 1) window.setTimeout(() => setIndex((value) => Math.min(questions.length - 1, value + 1)), 520);
  }

  function openSubject(next: string) {
    setSubject(next);
    setIndex(0);
    scrollTo("tests");
  }

  async function courseClick(course: Course) {
    fetch("/api/lead", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "Оплата курсу", name: "Клік по оплаті", phone: "", subject: course.title, score: course.price }) }).catch(() => undefined);
    scrollTo("contact");
  }

  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSending(true);
    const payload = { type: "Заявка", name, phone, subject, score: `${score}/${questions.length}`, correct: score, wrong };
    localStorage.setItem("nmthub-lead", JSON.stringify({ ...payload, createdAt: new Date().toISOString() }));
    try { await fetch("/api/lead", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); } catch { /* silent */ }
    setSending(false);
    setSent(true);
  }

  return <main className="site" id="home"><div className="orb orb-a" /><div className="orb orb-b" />
    <header className="header float-in"><button className="logo" onClick={() => scrollTo("home")}><span>NH</span><strong>NMT<span>Hub</span></strong></button><nav className="nav">{nav.map(([label, id]) => <button key={id} onClick={() => scrollTo(id)}>{label}</button>)}</nav><button className="header-cta" onClick={() => scrollTo("contact")}>Записатися</button><button className="menu-button" onClick={() => setMenuOpen(true)} aria-label="Відкрити меню"><Menu size={22} /></button></header>
    {menuOpen && <div className="mobile-panel"><button className="close-button" onClick={() => setMenuOpen(false)} aria-label="Закрити меню"><X size={22} /></button>{nav.map(([label, id]) => <button key={id} onClick={() => { setMenuOpen(false); scrollTo(id); }}>{label}</button>)}</div>}
    <section className="hero section"><div className="hero-text reveal-up"><div className="label"><Sparkles size={16} /> Підготовка до НМТ 2027</div><h1>Здай НМТ на максимум</h1><p>Пройди короткий тест і подивись, з чого варто почати. Після заявки ми підберемо формат занять під твій рівень і ціль.</p><div className="hero-actions"><button className="primary" onClick={() => scrollTo("tests")}>Пройти тест <ArrowRight size={18} /></button><button className="secondary" onClick={() => scrollTo("prices")}>Дивитися ціни</button></div></div><div className="hero-card reveal-up delay-1"><div className="score pulse-score">200</div><h2>200 — це не магія</h2><p>Це нормальний план, регулярна практика і спокійний розбір помилок. Залиш заявку — ми зв’яжемось і підкажемо, з чого почати.</p><div className="card-list"><span><CheckCircle2 size={17} /> Один екран тесту</span><span><CheckCircle2 size={17} /> Після відповіді — наступне питання</span><span><CheckCircle2 size={17} /> У фіналі видно правильні й неправильні відповіді</span></div></div></section>
    <section className="stats reveal-up"><article><strong>8</strong><span>предметів</span></article><article><strong>80</strong><span>питань</span></article><article><strong>{score}/10</strong><span>правильно</span></article><article><strong>{wrong}/10</strong><span>неправильно</span></article></section>
    <section className="section" id="subjects"><div className="section-head"><div className="label"><BookOpen size={16} /> Предмети</div><h2>Обери предмет</h2><p>Тест короткий. Він не замінює повну діагностику, але швидко показує, де вже впевнено, а де треба повторити.</p></div><div className="subject-grid">{subjects.map((item, itemIndex) => <article className={item === subject ? "subject interactive-card active-subject" : "subject interactive-card"} key={item}><span>{String(itemIndex + 1).padStart(2, "0")}</span><h3>{item}</h3><p>10 питань для швидкої перевірки рівня.</p><button onClick={() => openSubject(item)}>Відкрити тест</button></article>)}</div></section>
    <section className="section tests-section" id="tests"><div className="section-head"><div className="label"><Zap size={16} /> Тест</div><h2>{subject}</h2><p>Відповідай по черзі. Після кліку питання зміниться автоматично.</p></div><div className="single-quiz"><div className="quiz-progress"><span>Питання {index + 1} / {questions.length}</span><b>{score}/{questions.length}</b></div><div className="quiz-bar"><i style={{ width: `${Math.max(((answered || index + 1) / questions.length) * 100, 10)}%` }} /></div><article key={key} className={picked !== undefined ? (picked === question[2] ? "quiz-card single correct" : "quiz-card single wrong") : "quiz-card single"}><div className="quiz-top"><span>Без років. Просто питання.</span>{picked !== undefined && <b>{picked === question[2] ? "+1" : "0"}</b>}</div><h3>{index + 1}. {question[0]}</h3><div className="quiz-options">{question[1].map((option, optionIndex) => <button key={option} className={picked === optionIndex ? "picked" : ""} onClick={() => choose(optionIndex)}>{option}</button>)}</div></article><div className="quiz-actions"><button className="secondary" onClick={() => setIndex((value) => Math.max(0, value - 1))}>Назад</button><button className="primary" onClick={() => setIndex((value) => Math.min(questions.length - 1, value + 1))}>Далі</button></div>{answered === questions.length && <div className="quiz-result"><CheckCircle2 size={28} /><strong>Результат: {score}/{questions.length}</strong><div className="test-stats"><span>Правильно: <b>{score}</b></span><span>Неправильно: <b>{wrong}</b></span><span>Точність: <b>{percent}%</b></span></div><p>{recommendation}</p><button className="primary" onClick={() => scrollTo("contact")}>Записатися</button></div>}</div></section>
    <section className="section process"><div className="section-head left"><div className="label"><Target size={16} /> План</div><h2>Підготовка без хаосу</h2><p>Спочатку дивимось рівень. Потім збираємо план: теми, практика, повторення і контроль прогресу.</p></div><div className="process-grid"><article className="process-card interactive-card"><span>1</span><h3>Тест</h3><p>Учень проходить 10 питань і бачить стартовий результат.</p></article><article className="process-card interactive-card"><span>2</span><h3>Розбір</h3><p>Фіксуємо слабкі теми й не витрачаємо час на те, що вже виходить.</p></article><article className="process-card interactive-card"><span>3</span><h3>Заняття</h3><p>Працюємо в групі або індивідуально — залежно від цілі та темпу.</p></article></div></section>
    <section className="section benefits"><div className="benefit-card interactive-card"><Award /><strong>Фокус на балах</strong><p>Працюємо під конкретний результат, а не просто “проходимо теми”.</p></div><div className="benefit-card interactive-card"><Users /><strong>Нормальний темп</strong><p>Без тиску. Але з регулярністю, домашніми завданнями і контролем.</p></div><div className="benefit-card interactive-card"><ShieldCheck /><strong>Видно прогрес</strong><p>Після тестів зрозуміло, що вже стало краще, а що ще потрібно повторити.</p></div><div className="benefit-card interactive-card"><Star /><strong>Більше практики</strong><p>Менше сухої теорії. Більше завдань, розбору й повторення.</p></div></section>
    <section className="section" id="prices"><div className="section-head"><div className="label"><Star size={16} /> Ціни</div><h2>Формат під твою ціль</h2><p>Можна почати з групи, взяти індивідуальне заняття або одразу забронювати пакет.</p></div><div className="price-grid rich-prices">{courses.map((course, itemIndex) => <article className={itemIndex === 1 ? "price featured" : "price"} key={course.title}>{itemIndex === 1 && <span className="popular">Популярний</span>}<h3>{course.title}</h3><strong>{course.price}</strong><p>{course.text}</p><ul><li><CheckCircle2 size={16} /> План підготовки</li><li><CheckCircle2 size={16} /> Практика</li><li><CheckCircle2 size={16} /> Контроль прогресу</li></ul><button onClick={() => courseClick(course)}>Оплатити курс</button></article>)}</div></section>
    <section className="section" id="reviews"><div className="section-head"><div className="label"><Award size={16} /> Відгуки</div><h2>Що кажуть учні</h2><p>Коротко і по суті: що змінилось після підготовки.</p></div><div className="reviews">{reviews.map(([subjectName, author, text]) => <article key={`${subjectName}-${author}`} className="interactive-card"><div>★★★★★</div><h3>{subjectName}</h3><p>{text}</p><span className="review-author">{author}</span></article>)}</div></section>
    <section className="section contact" id="contact"><div><div className="label"><Phone size={16} /> Заявка</div><h2>Залиш заявку</h2><p>Напиши ім’я та телефон. Ми зв’яжемось і допоможемо вибрати формат занять.</p></div><form className="form" onSubmit={submit}>{sent ? <div className="success"><CheckCircle2 size={42} /><h3>Заявку прийнято</h3><p>Скоро з вами зв’яжемось.</p><button type="button" onClick={() => setSent(false)}>Ще раз</button></div> : <><label>Ім'я<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Ваше ім'я" required /></label><label>Телефон<input value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="+380..." required /></label><label>Предмет<select value={subject} onChange={(event) => setSubject(event.target.value)}>{subjects.map((item) => <option key={item}>{item}</option>)}</select></label><div className="result-pill">Результат тесту: <b>{score}/{questions.length}</b></div><button className="primary" type="submit" disabled={sending}>{sending ? "Надсилаємо..." : "Надіслати заявку"} <ArrowRight size={18} /></button></>}</form></section>
    <footer className="footer"><div className="logo"><span>NH</span><strong>NMT<span>Hub</span></strong></div><p>© 2026 NMTHub. Підготовка до НМТ.</p></footer>
  </main>;
}
